-- seed.sql

INSERT INTO games (developer, publisher, name, cover, genre, release_date, description) VALUES
('Valve','Valve','Portal','images/portal.jpg','Action','2007-10-10','Portal™ is a new single player game from Valve. Set in the mysterious Aperture Science Laboratories, Portal has been called one of the most innovative new games on the horizon and will offer gamers hours of unique gameplay. The game is designed to change the way players approach, manipulate, and surmise the possibilities in a given environment; similar to how Half-Life® 2''s Gravity Gun innovated new ways to leverage an object in any given situation. Players must solve physical puzzles and challenges by opening portals to maneuvering objects, and themselves, through space.'),
('Valve','Valve','Portal 2','images/portal2.jpg','Action','2011-04-19','Portal 2 draws from the award-winning formula of innovative gameplay, story, and music that earned the original Portal over 70 industry accolades and created a cult following. The single-player portion of Portal 2 introduces a cast of dynamic new characters, a host of fresh puzzle elements, and a much larger set of devious test chambers. Players will explore never-before-seen areas of the Aperture Science Labs and be reunited with GLaDOS, the occasionally murderous computer companion who guided them through the original game. The game’s two-player cooperative mode features its own entirely separate campaign with a unique story, test chambers, and two new player characters. This new mode forces players to reconsider everything they thought they knew about portals. Success will require them to not just act cooperatively, but to think cooperatively.'),
('Valve','Valve','Half Life','images/Half_Life.jpg','Action','1998-11-19','Classic FPS'),
('Valve','Valve','Half Life 2','images/half_life2.jpg','Action','2004-11-16','Reawakened from stasis in the occupied metropolis of City 17, Gordon Freeman joins Alyx Vance to lead a desperate human resistance. Experience the landmark first-person shooter packed with immersive world-building, boundary-pushing physics, and exhilarating combat.'),
('Valve','Valve','Team Fortress 2','images/team_fortress.jpg','Free to Play','2007-10-10','Nine distinct classes provide a broad range of tactical abilities and personalities. Constantly updated with new game modes, maps, equipment and, most importantly, hats!'),
('Westwood Studios','Electronic Arts','Command & Conquer - Red Alert','images/redalert.jpg','Real-time strategy','1996-11-22','The second game in the Command & Conquer series, Red Alert lets players command Allied or Soviet forces in an alternate-history conflict. Known for its fast-paced RTS gameplay and iconic FMV cutscenes.'),
('ConcernedApe','ConcernedApe','Stardew Valley','images/stardew_valley.jpg','Simulation','2016-02-26','You’ve inherited your grandfather’s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?'),
('Flashbulb Games','Flashbulb Games','Trailmakers','images/trailmakers.jpg','Adventure','2019-09-18','Build the ultimate vehicle and explore a vast open world filled with challenges and adventure. Play solo or team up with friends in multiplayer to conquer the toughest obstacles. With a thrilling campaign mode and endless creative possibilities, Trailmakers is the ultimate sandbox for adventurers.'),
('Maxis','Electronic Arts','The Sims 4','images/sims4.jpg','Simulation','2014-09-02','Play with life and discover the possibilities. Unleash your imagination and create a world of Sims that’s wholly unique. Explore and customize every detail from Sims to homes—and much more.'),
('Ubisoft Nadeo','Ubisoft','Trackmania','images/trackmania.jpg','Racing','2020-07-01','Trackmania combines easy-to-learn, hard-to-master racing with a fresh look and creative direction. A remake of Trackmania Nations, it features a free-to-play base game, track editor, online events, and car customization.'),
('Christian Whitehead, Headcannon, PagodaWest Games','SEGA','Sonic Mania','images/sonic_mania.jpg','Action','2017-08-15','Sonic Mania is an all-new adventure with Sonic, Tails, and Knuckles full of unique bosses, rolling 2D landscapes, and fun classic gameplay.'),
('Team17','Team17','Worms Armageddon','images/worms_armageddon.jpg','Strategy','1999-11-19','Those intrepid invertebrates return with a vengeance in the much-loved Worms™ Armageddon. It’s a whole new can of worms! It’s hilarious fun that you can enjoy on your own or with all your friends.'),
('Sonic Team','SEGA','Sonic Racing: Crossworlds','images/sonic_crossworlds.jpg','Racing','2025-09-25','Sonic Racing: CrossWorlds is a 2025 kart racing game developed by Sonic Team and published by SEGA. A spinoff in the Sonic the Hedgehog series, it incorporates characters and features from previous Sonic racing games, with new courses, customization, and crossover content.'),

